$newsFiles = Get-ChildItem -Path "content\news" -Filter "*.md" -File | 
    Where-Object { $_.Name -ne "README.md" -and $_.Name -ne "TEMPLATE.md" } |
    ForEach-Object { $_.BaseName } |
    Sort-Object -Descending

$shopFiles = Get-ChildItem -Path "content\shop" -Filter "*.md" -File |
    Where-Object { $_.Name -ne "README.md" -and $_.Name -ne "TEMPLATE.md" } |
    ForEach-Object { $_.BaseName }

$newsArray = ($newsFiles | ForEach-Object { "        '$_'" }) -join ",`n"
$shopArray = ($shopFiles | ForEach-Object { "        '$_'" }) -join ",`n"

$content = @"
// Auto-discovery configuration for news and shop
// This file is automatically generated by generate-index.ps1
// Run: .\generate-index.ps1 to update this file

window.contentIndex = {
    news: [
$newsArray
    ],
    shop: [
$shopArray
    ]
};
"@

Set-Content -Path "scripts\content-index.js" -Value $content -Encoding UTF8

Write-Host "✅ scripts\content-index.js generated successfully!" -ForegroundColor Green
Write-Host "   News articles: $($newsFiles.Count)" -ForegroundColor Cyan
Write-Host "   Shop products: $($shopFiles.Count)" -ForegroundColor Cyan
