// Auto-discovery configuration for news and shop
// This file is automatically generated by generate-index.ps1
// Run: .\generate-index.ps1 to update this file

window.contentIndex = {
    news: [
        '2025-10-15-digital-cats',
        '2025-10-11-lorem-kotiki',
        '2025-10-09-news-system-launched'
    ],
    shop: [
        'light-meow',
        'neon-reflections',
        'poster-set',
        'sticker-pack',
        'tshirt-zzarty'
    ]
};
